### PR TITLE
ux(docs): provide a release changelog

### LINKED ISSUE #670: Establish a documented release process

### PR DESCRIPTION
**Pull request by mightyiam**
Also set up a documented release process.

Fixes #670.

### CODE REVIEW

**Comment by mightyiam** [comment]
Of course, the first changelog will be produced with the next release.

**Comment by kuraga** [comment]
@mightyiam , `package-lock.json` has been added. Is that you expected?

**Comment by mightyiam** [comment]
@kuraga, yes. It's because a new dependency was added.

**Comment by kuraga** [comment]
@mightyiam , wouldn't we ignore it in Git?

**Comment by mightyiam** [comment]
I apologize. I wrote wrong. A `package-lock.json` already existed. This PR did not add it. It added many lines to it.

**Comment by kuraga** [comment]
Oh. That's I apologize.

**Pull request merged**
