### PR TITLE
fix: optimization judge svg

### PR DESCRIPTION
**Pull request by jingjing20**
use sel.startsWith('svg') replace sel[0] === s && sel[1] === v &&
sel[2] === g

### CODE REVIEW

**Comment by iambumblehead** [comment]
this is more compact and, if the regexp is memoized, faster
```javascript
/^svg[#.]/.test(sel)
```

**Comment by paldepind** [comment]
Thanks for the PR @jingjing20. Apologies for never taking a look at this. I'm closing this PR as this change has now been merged as part of another PR.

**Comment by jingjing20** [comment]
Ok

**Comment by jingjing20** [comment]
> Thanks for the PR @jingjing20. Apologies for never taking a look at this. I'm closing this PR as this change has now been merged as part of another PR.

OK

**Pull request closed without merging**
