### PR TITLE
Update `h` signature; children nodes can now be `undefined` or `null`

### PR DESCRIPTION
**Pull request by ornicar**
Required now that #226 is implemented.

### CODE REVIEW

**Comment by staltz** [comment]
I'd rather drop `MaybeVNode` and just write it straight inline

**Comment by ornicar** [comment]
Ok, squashed it in.

**Comment by ornicar** [comment]
This is still required to make use of #226. Anything blocking the merge?

**Comment by staltz** [comment]
Looks all good. Thanks!

**Pull request merged**
