### PR TITLE
style(package): use prettier default config

### PR DESCRIPTION
**Pull request by wclr**
This is a new version of https://github.com/snabbdom/snabbdom/pull/886

This adds prettier config and just formats all src files. Updated lint config. No changes to src/tests/etc logic.

Passes linting and tests locally.

### CODE REVIEW

**Review by mightyiam — CHANGES_REQUESTED** [review]
In order to be able to review the changes, this PR must be split into 2 commits. One commit is the configuration changes necessary to set this up and the other contains all the formatting changes that prettier makes.

What could help in doing that is disabling the prettier extension in the editor temporarily and also using prettier with some `--dry-run` flag or equivalent, for the first commit.

**Comment by wclr** [comment]
@mightyiam 
I thought about this, but those changes come along. You want me to make another try? )

**Comment by mightyiam** [comment]
> @mightyiam
> I thought about this, but those changes come along. You want me to make another try? I wouldn't like to do this, as I don't really see the reason.

Surely there are ways to prevent the changes from applying. I suggested two possibilities

> You may easily review the changes by filtering extensions of files that changed.

Some configuration files have not only meaningful changes but also formatting changes, so not convenient to review.

Please try splitting.

**Comment by jvanbruegge** [comment]
I am currently preparing a PR to simplify the tooling, where a bunch of files are moved around, I could also add prettier as part of that PR (with seperate commits)

**Comment by mightyiam** [comment]
> I am currently preparing a PR to simplify the tooling, where a bunch of files are moved around, I could also add prettier as part of that PR (with seperate commits)

I hope you're not removing things I'm happy about and worked hard at that would make me sad.

**Comment by jvanbruegge** [comment]
I don't think that I do. Just dropping webpack, the custom typescript plugin and the like

**Comment by wclr** [comment]
@jvanbruegge go ahead with adding prettier to your PR, use default settings as @paldepind said)

**Comment by jvanbruegge** [comment]
Closing in favor of #948

**Pull request closed without merging**
