### PR TITLE
Delete props only when they become undefined

### PR DESCRIPTION
**Pull request by nornagon**
This allows setting a prop to `0` or `false`.

### CODE REVIEW

**Comment by fix-fix** [comment]
This is a breaking change, isn't it?

**Comment by nornagon** [comment]
It doesn't seem to break the tests :)

**Comment by caridy** [comment]
yes, this is a breaking change. Also, typeof is slow for critical path. I don't fully understand the rational of this change though.

**Comment by staltz** [comment]
Well, I see the utility of allowing prop values like `0` and `false`, just need to use `if (props[key] == null)`.

**Comment by mightyiam** [comment]
#624

**Pull request closed without merging**
