### PR TITLE
chore(tools): remove un-needed dot files

### PR DESCRIPTION
**Pull request by iambumblehead**
remove un-needed dot files; `.node-version`, `.npmignore`, `.nvmrc`

`.npmignore` is not needed because package.json now specifies additive "files"
`.node-version` and `.nvmrc` are not needed because any node version from the last several years is fine

### CODE REVIEW

**Comment by iambumblehead** [comment]
the "vdom" keyword was added to package.json only to create some change that would trigger the CI because [CI failed on the first push.](https://github.com/snabbdom/snabbdom/actions/runs/6818914218/job/18545382556#step:4:145)
```bash
  ❌ Browser tests did not start after 20000ms You can
 increase this timeout with the testsStartTimeout option.
 Check the browser logs or open the browser in debug
 mode for more information.  (failed on firefox)
```

**Comment by paldepind** [comment]
Thanks @iambumblehead. I think this is great. All of these files create clutter and it's nice to only have as few as strictly needed.

**Comment by iambumblehead** [comment]
thanks for approving and accepting my PRs

**Comment by iambumblehead** [comment]
@paldepind @jvanbruegge I don't want to bother you with PRs you do not want... and so it would be great if you would triage issues and PRs when you are available. Many open issues have been resolved with PRs long-ago merged. For other issues, its not clear if solutions are wanted or not, for example its not clear if issues resolved with this PR are of any concern https://github.com/snabbdom/snabbdom/pull/1062

If there were fewer open issues and if open issues were deemed important, it would be easier to browse issues to know which PRs are wanted. For this reason, as an outsider, I think it would be cool if snabbdom would resolve or close outstanding issues and PRs.

**Comment by iambumblehead** [comment]
cc @kuraga to include them here as an interested person

**Pull request merged**
