### PR TITLE
debt: remove dist/ from VCS. fixes #481

### LINKED ISSUE #481: How about not tracking `dist` in VCS?
I feel against tracking build artifacts in VCS.

### PR DESCRIPTION
**Pull request by mreinstein**
as per the discussion in issue #481

### CODE REVIEW

**Comment by kuraga** [comment]
Thanks!

But shouldn't we generate it somewhere? For instance, in `prepublishOnly`?

**Comment by mreinstein** [comment]
> we generate it somewhere? For instance, in prepublishOnly?

Turns out we already do :)   https://github.com/snabbdom/snabbdom/blob/master/package.json#L61

**Comment by mreinstein** [comment]
@mightyiam it seems the build has been marked as failure due to failing commitlint messages. Is there an easy way to just re-trigger the build? They should be solved.

**Comment by mightyiam** [comment]
@mreinstein thank you for the PR. I already have one for this #549 😅

**Comment by mreinstein** [comment]
closing in favor of  #549 :)

**Pull request closed without merging**
