### PR TITLE
fix: generate valid javascript modules in build. fixes #963.

### LINKED ISSUE #963: feature request: update to esm modules
This script but it isn't valid esm https://cdn.jsdelivr.net/npm/snabbdom@3.0.1/build/h.js
```javascript
import { vnode } from "./vnode";
// should be as below
import { vnode } from "./vnode.js";
```
Please update this package to export esm as well.

If you are accepting PRs, I would be willing to try making a PR for this.

### PR DESCRIPTION
**Pull request by mreinstein**

### CODE REVIEW

**Comment by mreinstein** [comment]
#963

**Comment by jvanbruegge** [comment]
I would strongly prefer something like [this](https://github.com/GervinFung/ts-add-js-extension) instead of basically importing non-existent javascript files

**Comment by mreinstein** [comment]
> I would strongly prefer something like

@jvanbruegge done.

**Comment by kuraga** [comment]
@mreinstein , thanks very much!

@mreinstein , @jvanbruegge , some questions, please... As the result:
1. Are our output files scripts (`.js`) or modules (`.mjs`)?
2. Can we `import` them as ECMAScript Modules?
3. Can we `require()` them as CommonJS files?
4. Can we `import` them as TypeScript Modules (in a TypeScript project)?

Thanks!

P.S. https://2ality.com/ has articles about these (the 2022 state).

**Comment by kuraga** [comment]
@mreinstein , thanks! Now I see (and yes, this PR doesn't change globally introduced by 09f2d1ca5a16fd0b402209d90e58b97998efacef and 7af7e3f684f0854a3466a94ac4d1bb7737993875.

But yeah, it's nice to add an instruction for TypeScript projects...

**Comment by iambumblehead** [comment]
In the current master branch, `npm run build` produces a jsx.js file with a bad import.
```bash
$ grep \\.\/h build/jsx.js
import { h } from "./h"; // should be "./h.js"
```

I encountered the issue in another PR and patched the file with sed https://github.com/snabbdom/snabbdom/pull/1084/files#diff-2d40d3ee7ec7a92500d7f2dbb4ab60b274c089a6062d7c5ac0cf9fdc63eddfe1R14

------

https://github.com/snabbdom/snabbdom/pull/439
> Can we pause on this for a minute? We've already inundated the maintainers with a lot of material today. I'd like to get other existing PRs/issues resolved before we expand out into more discussions.

https://github.com/snabbdom/snabbdom/pull/957#issuecomment-1832581486
> Possibly, but I'm waiting for feedback from Jan. There's already a lot of stuff flying around today. I don't want to jam more activity in until he's had a chance to catch up.

These things don't feel good: "unpausing/unrelenting", "inundating", "expanding" and "jamming"

Please allow me to comment without casting such words and allow maintainers to represent their own feelings and positions to others.

**Comment by mreinstein** [comment]
You pinged _me_ and specifically asked for suggestions:

> mreinstein kuraga jvanbruegge feel free to give any suggestions or ideas

My suggestion is to chill for a second and give the other maintainers a chance to catch up before creating more material to parse. I never said you are not allowed to comment. If you don't want suggestions or ideas, don't ask people for them.

**Pull request merged**
