### PR TITLE
docs(docs): readme section on related packages

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
@mreinstein do you feel this would close #640 ?

**Comment by paldepind** [comment]
I think we should collapse this with the current "Structuring Applications" section. What I mean is, keep the text that this PR adds, rename the "Structuring Applications" section to "Related Projects" to broaden its scope, and then perhaps sort the list into a few rough categories.

**Comment by mreinstein** [comment]
@paldepind @mightyiam I think for the sake of making the readme shorter and easier to read, we should move this stuff to a separate markdown doc. Maybe just like `related-projects.md`.

Making the initial documentation shorter is almost always a good thing. :)

**Comment by paldepind** [comment]
I think mentioning the npm tag and linking to the search results for the tag on npm is nice. I still agree with my comment above, but merging this PR for now as it's still an improvement.

**Pull request merged**
