### PR TITLE
Fix compatibility issue of String.prototype.startsWith

### PR DESCRIPTION
**Pull request by zhulongzheng**
`String.prototype.startsWith` is in ES2015 specification and is not ready for some devices.

### CODE REVIEW

**Comment by mightyiam** [comment]
This kind of thing is easily solved in the end-product using a polyfill, right?

**Comment by nunocastromartins** [comment]
This is similar to the discussion in #192. Even though it shouldn't matter much performance-wise, `indexOf` does search through the whole string.
Maybe do: `name[0] === '-' && name[1] === '-'`?

**Comment by zhulongzheng** [comment]
But you must read the source code to find what causes this problem, I don't think it's normal users' job.

**Comment by paldepind** [comment]
Oh. That is a mistake. Would you change the PR so the check is done like this:

```js
name[0] === "-" && name[1] === "-"
```

In #192 and #213 a similar thing was discussed.

**Comment by jbucaran** [comment]
@paldepind Why not `name.substr(0, 2) === "--"`?

**Comment by zhulongzheng** [comment]
@paldepind Updated!

**Comment by staltz** [comment]
> Why not name.substr(0, 2) === "--"?

Performance

**Comment by staltz** [comment]
This should be good to merge.

**Comment by paldepind** [comment]
Looks good. Thank you @zhulongzheng :smile:

**Pull request merged**
