### PR TITLE
Explain insertBefore in README

### LINKED ISSUE #395: Error: insertBefore when reusing vnodes
Reproducable example:
```js
var sharedNode = h('div', {}, 'Selected');
var vnode1 = h('div', [
  h('div', {}, ['One']),
  h('div', {}, ['Two']),
  h('div', {}, [sharedNode]),
]);
var vnode2 = h('div', [
  h('div', {}, ['One']),
  h('div', {}, [sharedNode]),
  h('div', {}, ['Three']),
]);
patch(vnode0, vnode1);
patch(vnode1, vnode2);
```
This example crashes on the second `patch`.
The reason is that when the actual DOM node for `sharedNode` on position two is created, it assigns it as `vnode.elm`. The `vnode` is still that same `sharedNode`, that the third node still has a reference to (as it is not yet processed). When the third node gets created, it tries to do `insertBefore` with `vnode.elm` which is **not** the actual elm from the last patch (on position 3), but the new dom node of `sharedNode` created in **this** patch (position 2). Thus the `insertBefore` crashes as the element is not a child of the parent of the third node.

Note that this issue only happens in this direction (first insert, then remove) if you swap the two patches this does not happen, as first the node gets removed (and thus the reference) and then a new one gets inserted

This is the cause for https://github.com/cyclejs/cyclejs/issues/713

I am not sure what is the best way to solve this.

### PR DESCRIPTION
**Pull request by jvanbruegge**
fixes #395

### CODE REVIEW

**Comment by paldepind** [comment]
Looks good.

Personally I prefer to wrap elements like that in a function:

```
var sharedNode = () => h('div', {}, 'Selected');
```

And then I call them in my views. This also ensures a fresh vnode on every patch.

What do you think about suggesting that as an alternative as well?

**Comment by jvanbruegge** [comment]
Added it

**Comment by jethrolarson** [comment]
Thanks for putting this in, I found it useful today :)

**Comment by staltz** [comment]
Seems like it was approved by enough people, and it's just docs, so I'll merge. :)

**Pull request merged**
