### PR TITLE
Fix for #360 error in IE/Edge

### PR DESCRIPTION
**Pull request by whitecolor**
Binding raf to window resolves the error.

### CODE REVIEW

**Comment by paldepind** [comment]
Hi @whitecolor. Thanks a lot for the fix to the error :+1: 

Would you mind adding a test that fails without the patch? That would be really nice. We prefer having tests for all bugfixes.

**Comment by whitecolor** [comment]
Look at the changes, there is actually nothing special to test.

As a see tests are not running currently at all because of some error not related to this PR. If the test for `requestAnimFrame` pass then it will be ok, if such test exists...

**Comment by paldepind** [comment]
What I mean is, the PR fixes a bug in IE/Edge. It would be nice to have a test that triggers that bug in IE/Edge.

**Comment by whitecolor** [comment]
in IE you just can not do
```js
const raf = window.requestAnimation
raf(() => ...) // will trigger the error, so have to bind first
```

Don't know how tests here work in this repo yet.

But I think probably this test should trigger:
https://github.com/snabbdom/snabbdom/blob/master/test/style.js#L102

Is it passing in IE? Are tests tunned to do IE  testing in CI?

**Comment by whitecolor** [comment]
`Edge` will soon anyway move to `webkit`, though not tomorrow of course.

**Pull request merged**
