### PR TITLE
chore(tools): remove un-needed dot-files; .prettierignore

### PR DESCRIPTION
**Pull request by iambumblehead**
This PR removes prettier-formatted trailing-comma and removes the .prettierignore (prettier continues to ignore build and coverage directories after the file is removed.

### CODE REVIEW

**Comment by paldepind** [comment]
Thanks.

Since this changes the Prettier configuration, should Prettier be re-run as part of this PR to ensure that future commits will not contain these formatting changes?

**Comment by iambumblehead** [comment]
I wasn't sure when to format them. A related PR includes a job to lint and prettier-check all files https://github.com/snabbdom/snabbdom/pull/1068

We could format files in chunks, for example,
 1. first PR, format md files such as README and CHANGLOG
 2. second PR, format json files, eslintrc and package.json
 3. third PR, format src/ and test/ files
 4. fourth PR format everything else
 5. after all files are formatted, update the linting job to check prettier format

I will apply prettier formatting to *md files in this PR. If you want remaining files formatted here they can be formatted as well.

**Comment by iambumblehead** [comment]
@paldepind .md and .json files are now prettier-formatted in this PR. Do you want to format remaining files here or should we use separate PR?

**Comment by paldepind** [comment]
I don't have any strong preferences as long as we get everything formatted in the end :)

If you want I can merge this PR as is and the remaining formatting can be a separate PR or you can update this PR with the remaining formatting and then I'll merge.

**Comment by iambumblehead** [comment]
@paldepind okay, it would be my preference to merge this PR now.

The next PR will format the remaining files.

**Comment by paldepind** [comment]
Great! Thanks for the PR.

**Pull request merged**
