### PR TITLE
chore: deprecate standalone UMD bundles

### LINKED ISSUE #481: How about not tracking `dist` in VCS?
I feel against tracking build artifacts in VCS.

### LINKED ISSUE #498: Checked in built UMD bundles out-of-date with source code
Last `dist` rebuild seems to be 3ed3a2a1a8b98eab19021d6988f3f4af25b606c8.

Commits since: 

f49c793eb4288d2a12b4de2d1bc477d9413f1479
f8774a96f5debaa2f00c3918559c497088840528
0c7f9ddd16ac2585267fafaab55a89440b819485
69294d8cb6565e5ae58c9b4043a22e6d3bdf063d
5035aed23a5695d9bf7a9aadcb0d9ff73e7c9b15
f54fb9b59c23f737e744e7d99f64e05fbdd70db3
8edc47fe750b3a70bcfc680d8e7f47f000680f01
0db9e8b038fbece9e724441fa5ac81c92b4bb444
5b5576f1bd96b8041139ed2b9401cea13ac58cdb
d9ff8da599597d0e1aeead83d8e7be2a902bf555
3ae871dd825d0906bb23bbe4e3701e7b271a4329
0881343e01911416c8e39a5dae665089643e1357
5a3ae5e14be44aef5260599f241e48a0ac52490d
c1854450b3ef23d8b24ba537aa4bec207a23fe9a
c2e66b5eb1450aa5a175d1ad2bf21e1c1ba8db9d
7ff8d13b4e5a037ac3a43519e746db26dc2c0173
dcdde2e8696bb3378a91106f1ef7206d17e65590
5fd1cec46cd48a3b26a283e71c29dc261ae9ee95
7c9a7acc1de136de3616c05cc3de58a01b59f964
35796cb124f8eeff93ed60f54e01babc0a5c9f31
52cd3eec364d0dde481a17e0061a6fdd85fdbfc2
a907828f1274bce38b0f4b33561224af749199e6
8b66f53bc117aef9eeccf8468f99c2f577c8e103
21511f305821f13a81ee873b9aa1780fa7456ef9
32a0ff3733c7ea16bdce82cef6bdcfc50ad2601e
9053f07131d20831333026d81eed78092d02bab4
4d07d0c39be4f7242930ebe46ca8a1959ab78a8e
98e1dc1f266c03a48b5ba5f63d071c862a6e4902
6c5549b0a092461d6f4a1987f41dac7b51f11a95
809caa147dfa5257d4281de0452be1bae8a88649
3dbf18e3a3b09909dfc71648c4934d13e20fa459
4b19aebd5e82eb8b7fc93946798bad6b8df3ad99
b39ada9ea4833524ea8132b785d1d73b4a765277
4243938d6af9c8232455410daf5b6b8009a6d9d9
808944d2f31c4e85e256ac2f9c6356803f1a5dcc
54b6b4507c90326b79a141a1ec71f485973261ad
6e86a5af5d68e9b5e296d415748f61015effbbe9
f307db46e3d08f86cf216d6799abc3da35d3b1a0
3f858078f013119c0c0b2a34484ba856e36a5af0
98e9cdb513115f3d84b9146f9c3280aad262a1f5
e77ecfc8922e39d2afd412addc02e5fb175597fe
79098d381f16d6fece22f05b7bda4580c6746ecf
179940d13c10f5ffcbda27071d0be35de267f28e
9033c58d6701a40fe924c85b8527e5859818fd30
dcbc1e10c76e46a6543668e12552d9f0b93b5dd4
f2b83d129040bc17698b0d5bb288dba6e8569617
529b46c8cee369b0e4ee8694d8b6dc03ede80e51
64c9bfe2b89288fdea005a2f2fbac57ba6a7c8b6
3e87660517f3940ad6f39b2877bd6b9931e40b9d
d3d4f0850e1be76480bdf8cd92bc69e35c8af893
ae3703d1a4e82e6654f660594774fb33018dfd99
47f3afd9ed47e4082898a732cb4f4f8c15f711a7
7e09d27f5680de198b7b363f574f531f4f1aa180
66f2e1886866038da17e5bf8bf66724d09185fe5
1ca15843343497f810fb5a7b568d7e4982f7ca45
b40ab1ca46cec8c65cd4478174eba1fe8b209b37
63a0c041c740f9c40836b642f51fb6f777d592bb
8787d60221373925c71e4e973b7fe040be62fdba
de104c01dfb58279cd686856e5557aca7bfec64a
dcce583bd261fa04f840595c9d7fe48fe311a13c
4e25f868b32882b852c4ed6d67e3c48f951d22e1
1f399d6ddef480d33d0da01907a85d2c2a6427e0
a0518b9a008bbb29f2600f2dfe5fd3b606ec9fb1
ff594946493cf84eff52ae28b6d6e9ff22017c19
e4efc1dcfd58fc86bb138e839a4051781b32cdb9
256e35f63bfd05618634c92e29b1563cc8420ff8
fab31f35621126a462e3ee3a1aea77ce1782e15f
2b56e249530e1e2023be877ce2e6930be0390a61
9a68a1e8a5b57ba3b6c781a2023d02ee88151f72
0a3bc6fdf4cca35861a7583fe568ff87b496102e
5c0f3db753042cd148d4e17342dea61068ad1667
d0cabc971227b36e3753bc3a938a10e9acbe1b15
db3100d3de4d16332707cc05df897df474089ed9
81da0c124257d393e29796a13e92f6f3016ac20d
f66f919960ae8be0539e2fe98537948977a7d326
425a6b2dedbe061799d100df41acdbe5f7e7001d
3b04714e81645be26724c64c03d87c78a1a5fe13
29b2829f16f57f88267cefae009f319647eb2e93
695da13ec5827307ca179e02a5ab0394a2df5699
3c0f50af426d1956f85fcae6cecbc0084906fa9b
6a632c28727ba194f40ffa8f921171f27a778502
e034e966a458504dbcc8361cff6a16e9a976d355
80603c28f358c8b7603d6555134b5cb20378d9c4
2e73a926cdcbec30e712bed24973d13e5e18c089
a34ffffffac32be4efac483c580496ae1ff76ae0
665d9d39ff874955254d89b381c392a6ae4e94b1
f7c3b0c216c06e4175e01fb93f1aca06618902e4
276f78d8595043e92396355094e0d142af19c8ec
102fb5940cb357d1c45faf28a175cf0693c113cb
00129c25ab4e1627cc7feae3fb04f3af35fb4e8a
953a32675700eee04c0d227810ec75fcacb7ee78
009516269957d318dfbef116cdf8584402bb5949
4455e73e9fc7c4e8df093276349b03efc5f82428
93787151e24c31240852c179aa753132f9be3ff5
1c4bfb76acc69c991c9b980418fabedbdc447dd9
3fe95cccde9bff2cbd3088df86217f36da84fd0d
d0ddf15ec4ccd217212157fa7768195d3d101821
053a387559478e40a25a27a38c9c9bcb08554886
37a522dfbd992ce6a20bf10cfe6b38b8eb0c865e
efda964ddb8f396403ba7cb1987f77b84d984793
b9f2db2e60eb0a21db409486c5015d4edd929a3f
b4d69aea97a7e57e8642d5401f9e36f6e566294f
1a8892c35a1e8f7218b8d81c49bbbda26ec0da86
fd302951a82a9b067e660563c6a9427a5779d56a
006133228a3e2b7c72541464bfd311b11de87251
730f6f89af1b7c17f6ff03bd3ab8b6ae4f5b9f75
d7a38d71b7ce8d6f0d4ec2838c5679e3aaa2bcea
093367e645240f83df518862b5c8c74df3a54a13
584f2c5334c3f9c6909a811fb28d52b83abb6530
3438b7480198289c638e65d195eccd97bb42afcf
fb04f628f37d4e56758733a1b88dd990fe773609
410d2b3a272067520a3a1595ae6f22679f69e3b4
2ab6f3dedf12441e8bbc85d6547d30e1637c7ba1

Since the releases since the last build seem to be patch-only, it suggest that a rebuild-commit would be a PATCH version.

I could investigate further and attempt to fix but I really suggest #481.

### LINKED ISSUE #514: gulp is broken
Running `$ npx gulp` results in:

```text
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/shahar/src/snabbdom/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/shahar/src/snabbdom/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/shahar/src/snabbdom/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
```

### PR DESCRIPTION
**Pull request by mightyiam**
The standalone UMD bundles provided in the npm package under `dist` will
no longer be updated. They are already several commits behind. See issue

Closes #498. Closes #514. Closes #481.

### CODE REVIEW

**Comment by paldepind** [comment]
I'm 👍 for removing the UMP modules. I've never used them myself anyway, and I'm guessing in this day most people are bundling themselves anyway.

I don't like the idea of deliberately publishing new versions with outdated UMP modules. That could give people the idea that they're staying up to date when they really aren't. Compared to that I'd rather just do a breaking change release and remove them immediately.

What about doing the next release as `1.0.0`? Snabbdom has been production-ready for many years now so it seems right to me. I don't think it has to be a big deal implying some sort of "perfect" or "improved" Snabbdom. But staying at `0.x.x` seems wrong and this breaking change seems as good an occasion as any.

**Comment by kuraga** [comment]
Moreover should we compile something at all?..

**Comment by mightyiam** [comment]
@paldepind, I'm happy to learn that's your attitude.

@kuraga this is a TypeScript project. I feel the least we should compile is to ES modules. We currently compile to both ES modules (but with a `.js` extension) and to CommonJS. There is likely an existing issue in the tracker open for discussion on compile targets. Could you please expand there or in a new issue on your suggestion?

**Comment by kuraga** [comment]
@mightyiam no, no, it wasn't a suggestion :) It was a rhetorical question :) Yes, correct question is "Which compile targets should we do?" But which issue do you mean?

> ES modules (but with a `.js` extension)

Hm...... Hmmmmmmmmm....... I'm not sure...... (and its NOT a rhetorical :)) But there is #516 for such discussions.

**Comment by kuraga** [comment]
So what's the future of this patch?

**Comment by mightyiam** [comment]
@kuraga replaced by #549 .

**Pull request closed without merging**
