### PR TITLE
Enable some ESLint rules

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by paldepind** [comment]
PR seems to do more than just enable the `one-var` rule. Semicolons are gone? 🤔

**Comment by mightyiam** [comment]
Had a glitch there. Ready for review!

**Comment by paldepind** [comment]
I don't think we should remove semicolons. That's pretty atypical.

**Comment by mightyiam** [comment]
@paldepind changed semicolons to always. Rebased.

**Comment by mightyiam** [comment]
Hold on. There's an error.

**Comment by mightyiam** [comment]
OK cool. I much prefer no semicolons but that should not hold up the rest of the rules in this PR.

**Pull request merged**
