### PR TITLE
Added fully bundled version

### PR DESCRIPTION
**Pull request by Risto-Stevcev**
Here's a fully bundled version. I named it `snabbdom.js` and `snabbdom.min.js`, and just created `snabbdom_init.js` for those who want to manually wire everything.

https://gist.github.com/Risto-Stevcev/2c6ff7ee10b52756293cde08b0c6447c
http://jsbin.com/dahaluweqe/edit?html,console,output

Can you bump the version after reviewing this? I want to include snabbdom as part of [CLJSJS](https://cljsjs.github.io) asap! :smile:

### CODE REVIEW

**Comment by grimalschi** [comment]
New built snabbdom.js is blocked for adding new modules.

First we need to add #121, and after this you will be able to use standalone version of snabbdom and add new modules.

**Comment by Risto-Stevcev** [comment]
@grimalschi I'm not following why this would have to wait for #121. The you can still use snabbdom_init.js with any modules you want to include if you don't want to include all of the modules.

**Comment by grimalschi** [comment]
@Risto-Stevcev I am not talking about snabbdom_init.js - i am talking only about snabbdom.js, which exports already initialized patch with default modules and without any possibility to add new modules.

**Comment by Risto-Stevcev** [comment]
@grimalschi Oh, so you mean custom modules? gotcha.

**Comment by paldepind** [comment]
Thank you for this PR @Risto-Stevcev. I am sorry for being so awfully slow to respond. I have, however, been thinking about this issue. I'm wondering if it would be better to make the default bundle the `init` one and a `snabbdom-patch` bundle that is one with modules bundled in.

If we additionally create browser builds of the modules it seems like we wouldn't need #121.

**Comment by Risto-Stevcev** [comment]
@paldepind Sure, I'll update it

**Comment by Risto-Stevcev** [comment]
@paldepind *I'm poking you to respond* :wink:

**Comment by paldepind** [comment]
No problem :smile: Sorry for not responding. Will you fix the conflicts in the PR? That would be really nice. :+1: Then I'd merge it in.

**Comment by Risto-Stevcev** [comment]
@paldepind Updated it :slightly_smiling_face:

**Comment by paldepind** [comment]
Sweet. Thank you :smile_cat:

**Pull request merged**
