### PR TITLE
feat: optimise detection of data and svg names

### PR DESCRIPTION
**Pull request by iambumblehead**
using these regexp tests would close two outstanding PRs
 1. https://github.com/snabbdom/snabbdom/pull/1037, optimize data attribute
 2. https://github.com/snabbdom/snabbdom/pull/1033, optimize svg selector

### CODE REVIEW

**Comment by kuraga** [comment]
(there is a smile of the old man)

https://github.com/snabbdom/snabbdom/pull/996#discussion_r786320401

**Comment by paldepind** [comment]
Out of the possible solutions, I would say that say that the one using `startsWith` is the easiest to read, but I think we should go with the most efficient solution.

Is there any evidence to suggest that using regexes is the fastest solution?

**Comment by paldepind** [comment]
I don't see how the regex test not throwing on non-strings is of much use. Passing anything but a string is an error anyway and does not have any use.

Since all three options are easy to understand and don't have any ramifications for the rest of the code, I think the key concern here is to pick the most performant version.

Thanks a lot for creating a benchmark, I think that is very useful to guide the decision here. Correct me if I'm wrong, but what I'm seeing is that the regex version is the slowest option. The benchmark tool outputs operations/second, so a higher number is better. This also matches what we see, for instance, `equalityFull` is clearly going to be slower than `equality`, and it has a lower number. So, it seems that using `startsWith` is the fastest option.

**Comment by iambumblehead** [comment]
> The last number is the rate of operations measured in ops/sec (higher is better).

Excuse the confusing summary I gave originally, I was reading the results wrong myself...  Yes, you are correct: regexp is least performant and startsWith is most performant. I'll update this PR to use startsWith.

**Comment by iambumblehead** [comment]
I didn't expect the PR to be closed...

**Comment by paldepind** [comment]
Ok, great, then we agree on the benchmark 🙂. I think using `startsWith` is best as well.

Dunno why the PR got closed, but GitHub won't let me reopen it, so I think you'll have to create a new one.

**Pull request closed without merging**
