### PR TITLE
refact: Small part of the grammar optimization

### PR DESCRIPTION
**Pull request by OctupleSakura**
Hi, I saw a small part of the source code that I could optimize
If you feel ok，Can you merge the branch ? 
Thank ~

### CODE REVIEW

**Comment by OctupleSakura** [comment]
sorry, ci prompts "testem: not found" , Is this test config setting problematic?

**Comment by mightyiam** [comment]
I've discovered the issue, as well, @OctupleSakura, and reported it as #426. There's a pull request open for it, as #427.

**Comment by OctupleSakura** [comment]
@mightyiam Thanks for your reminder. But no one is fixing it now..

**Comment by mightyiam** [comment]
It was only 2 days ago. Yes, this project seems to require some more love.

**Comment by paldepind** [comment]
Thanks for the PR @OctupleSakura. Looks great :+1:  The properties must have been missed when the project was originally ported from ES5 to ES6.

**Pull request merged**
