### PR TITLE
Resolve checkbox race condition

### PR DESCRIPTION
**Pull request by Fresheyeball**
We should check if the key is "checked" as well as "value" to see if the dom got out of sync.

Resolves: #950

### CODE REVIEW

**Comment by jvanbruegge** [comment]
This looks good to me, what do you think @mreinstein ?

**Comment by mreinstein** [comment]
should be re-submitted as a clean PR, and there should be test(s) included, when that's done I'm on board. 👍

**Comment by Fresheyeball** [comment]
@mreinstein sorry, but this is probably all the time I can devote to this. I made a thorough bug report and supplied a fix. I don't think I am going to have time to figure out your testing and CI toolchain as well, unfortunately.

**Comment by mreinstein** [comment]
>  I made a thorough bug report and supplied a fix

I definitely appreciate your hard work, thank you very much! ❤️ 


>  I am going to have time to figure out your testing and CI toolchain as well, unfortunately.

I totally hear you.  I also struggle with the over-engineered nature of the toolchain.

Can you at least provide a basic unit test here in the comments? I'm happy to take your PR and add the necessary ceremony/formality to get this merged in.

thanks again for your help!

**Comment by Fresheyeball** [comment]
@mreinstein for the unit test example, see the linked issue :)

**Comment by mreinstein** [comment]
Will try to find some time this week to re-package the fix and test in a clean PR.

**Comment by jvanbruegge** [comment]
closing in favor of #955

**Pull request closed without merging**
