### PR TITLE
compress the logo image to reduce size 50%

### PR DESCRIPTION
**Pull request by mreinstein**
reduces the size of the snabbdom module quite a bit.

### CODE REVIEW

**Comment by mightyiam** [comment]
@mreinstein I don't understand. Currently, there is nothing to reduce the size of, because there is no raster image in the repository.

**Comment by mreinstein** [comment]
Huh, that's really odd.  I could have sworn I saw the .png file in my installed `node_modules/snabbdom/` directory.

Oh well. It won't affect the package download size, but it might be nice to cut down the size of any image delivered over the web anyway, whether it's viewed over github or in the npm package. Maybe you'll find this optimization useful.

**Comment by paldepind** [comment]
@mreinstein Probably because it was changed only 5 days ago: https://github.com/snabbdom/snabbdom/commit/4730583ed2bc049f03c33f988d1712616f711edf

**Comment by mightyiam** [comment]
Yup. There's no need for a raster image. Anyone could make one out of the source SVG. Thanks, though!

**Comment by mreinstein** [comment]
> no need for a raster image

yeah, I understand that. I'm glad it's an svg now, but this raster image came from the snabbdom repo, I didn't make it. :)

**Comment by paldepind** [comment]
Thanks for the PR @mreinstein. Would've been a good idea if it wasn't for the recent change to SVG 👍  😄

**Comment by mreinstein** [comment]
I'm definitely super happy that it's svg. Everything we can do to make assets smaller and promote that amazing image format is a step forward. :)

**Pull request closed without merging**
