### PR TITLE
chore(tools): enable npm run example

### PR DESCRIPTION
**Pull request by shfshanyue**
`npm run example` run example locally and make debugging a lot simpler.

lint fail and fixed by #981

### CODE REVIEW

**Comment by jvanbruegge** [comment]
I fixed the CI in master, could you rebase please?

**Comment by shfshanyue** [comment]
it's ok.

> I fixed the CI in master, could you rebase please?

**Comment by jvanbruegge** [comment]
This looks good, could you add a rewrite from "/" to "/examples" so that one does not have to search for that folder? (https://github.com/vercel/serve-handler#redirects-array)

**Comment by shfshanyue** [comment]
thank you, I has add a redirect from "/" to "/examples".

**Comment by jvanbruegge** [comment]
Perfect, thank you

**Pull request merged**
