### PR TITLE
call handleEvent if handler is object

### PR DESCRIPTION
**Pull request by Reon90**
According to the spec, we can pass object with handleEvent method to addEventlistener.

### CODE REVIEW

**Comment by AlexGalays** [comment]
True, although I never saw anyone use this form. Is it really that useful when using a VDOM lib ?
Also, you can create your own modules if the default ones are not exactly how you would want them.

**Comment by Reon90** [comment]
Otherwise, I have to use the bind(this). It looks ugly. 
It's a bad practice in some companies.

**Comment by AlexGalays** [comment]
Agreed about bind(this). You're not using ES6/babel/typescript by any chance? Then the `=>` notation would replace bind(this).

**Comment by hville** [comment]
I sugested the same in #189 and closed it due to lack of interest. I still think it is a better pattern.

**Comment by mightyiam** [comment]
Closing this because #189 is closed. But if you'd like to reopen that issue, feel free to do so.

**Pull request closed without merging**
